export function isPlainObject(value: unknown): boolean;
export function asPlainObject(value: unknown): object | null;
export function shouldPlainObject(value: unknown): object;
export function isError(value: unknown): boolean;
export function asError(value: unknown): Error | null;
export function shouldError(value: unknown): Error;
export function isRegExp(value: unknown): boolean;
export function asRegExp(value: unknown): RegExp | null;
export function shouldRegExp(value: unknown): RegExp;
export function isMap(value: unknown): boolean;
export function asMap(value: unknown): Map<unknown, unknown> | null;
export function shouldMap(value: unknown): Map<unknown, unknown>;
export { isPlainObject as isObject, asPlainObject as asObject, shouldPlainObject as shouldObject };
